services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn inventory_app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgresql_zcaw_user:pzb5N1HjTsLF7LAM2p6SVKCbC4LFW1fq@dpg-d4tmv0n17kns73cnar1g-a/postgresql_zcaw"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "inventory-system-3614.onrender.com"